"use client";

import { useCallback, useEffect, useRef, useState, type RefObject } from "react";
import { getShareableText, languageToSpeechCode } from "@/lib/explanation-utils";
import { stripMarkdown } from "@/lib/sanitize";
import { POPUP_BLOCKED_MESSAGE } from "@/lib/copy";
import type { Explanation } from "@/lib/types";

type FlashState = "idle" | "copied" | "shared";

export function useResultActions(
  explanation: Explanation | null,
  contentRef: RefObject<HTMLElement | null>
) {
  const [flash, setFlash] = useState<FlashState>("idle");
  const [speaking, setSpeaking] = useState(false);
  const [popupError, setPopupError] = useState<string | null>(null);
  const flashTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (flashTimeout.current) clearTimeout(flashTimeout.current);
      if (typeof window !== "undefined" && "speechSynthesis" in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const flashFor = useCallback((state: FlashState, ms = 1300) => {
    setFlash(state);
    if (flashTimeout.current) clearTimeout(flashTimeout.current);
    flashTimeout.current = setTimeout(() => setFlash("idle"), ms);
  }, []);

  const copy = useCallback(async () => {
    if (!explanation) return;
    await navigator.clipboard.writeText(getShareableText(explanation));
    flashFor("copied");
  }, [explanation, flashFor]);

  const share = useCallback(async () => {
    if (!explanation) return;
    const shareData = {
      title: `ELI5: ${explanation.topic}`,
      text: getShareableText(explanation),
    };

    if (typeof navigator.share === "function") {
      try {
        await navigator.share(shareData);
        return;
      } catch {
        // User cancelled the native share sheet — fall through to clipboard.
      }
    }

    await navigator.clipboard.writeText(`${shareData.title}\n\n${shareData.text}`);
    flashFor("shared");
  }, [explanation, flashFor]);

  const downloadPdf = useCallback(() => {
    if (!explanation) return;
    const printWindow = window.open("", "_blank", "noopener,noreferrer");
    if (!printWindow) {
      setPopupError(POPUP_BLOCKED_MESSAGE);
      return;
    }
    setPopupError(null);

    const safeTitle = explanation.topic.replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const bodyHtml = contentRef.current?.innerHTML ?? "";

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8" />
          <title>${safeTitle} — ELI5</title>
          <style>
            body { font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 40px; color: #14162e; line-height: 1.65; }
            h1 { margin-bottom: 4px; }
            .meta { color: #6f7193; margin-bottom: 28px; font-size: 0.9rem; }
            pre { white-space: pre-wrap; background: #f3f4f6; padding: 14px; border-radius: 8px; overflow-x: auto; }
            code { background: #f3f4f6; padding: 2px 4px; border-radius: 4px; }
            pre code { background: none; padding: 0; }
            blockquote { border-left: 3px solid #7c8bff; margin: 1rem 0; padding: 0.4rem 1rem; color: #51547a; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
          </style>
        </head>
        <body>
          <h1>${safeTitle}</h1>
          <p class="meta">Generated by ELI5 — Explain Like I'm 5</p>
          ${bodyHtml}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }, [explanation, contentRef]);

  const toggleSpeech = useCallback(() => {
    if (!explanation || !("speechSynthesis" in window)) return;

    if (window.speechSynthesis.speaking) {
      window.speechSynthesis.cancel();
      setSpeaking(false);
      return;
    }

    const utterance = new SpeechSynthesisUtterance(stripMarkdown(getShareableText(explanation)));
    utterance.lang = languageToSpeechCode(explanation.language);
    utterance.rate = 0.98;
    utterance.onend = () => setSpeaking(false);
    utterance.onerror = () => setSpeaking(false);
    setSpeaking(true);
    window.speechSynthesis.speak(utterance);
  }, [explanation]);

  return { flash, copy, share, downloadPdf, toggleSpeech, speaking, popupError };
}
